add alias < "riposa"> to < "rest"
add alias < "impara < modulo" > to < "learn < modulo"
add alias < "esegui < codice" > to < "run < codice"
add alias < "esegui < codice > quì" > to < "run < codice > here"
add alias < "ripeti < codice" > to < "repeat < codice"
add alias < "interrompi < n > volte" > to < "break < n > times"

add alias < "definisci < prototipo >< corpo" > to < "define < prototipo >< corpo"
add alias < "restituisci < valore" > to < "return < valore"
add alias < "aggiungi alias < alias > a < funzione" > to < "add alias < alias > to < funzione"

add alias < "crea < variabile > con < valore" > to < "create < variabile > as < valore"
add alias < "imposta < variabile > a < valore" > to < "set < variabile > to < valore"
add alias < "valore di < variabile" > to < "value of < variabile"
add alias < "tipo di < valore" > to < "type of < valore"
add alias < "condividi < variabile" > to < "lend < variabile"
add alias < "prendi < variabile" > to < "borrow < variabile"
add alias < "aggiungi nome < nome > a < variabile" > to < "add name < nome > to < variabile"

add alias < "se < condizione >< codice" > to < "if < condizione >< codice"
add alias < "altrimenti se < condizione >< codice" > to < "else if < condizione >< codice"
add alias < "altrimenti < codice" > to < "else < codice"

add alias < "dì ..." > to < "say ..."
add alias < "chiedi < domanda" > to < "ask < domanda"

add alias < "primo > è uguale a < secondo" > to < "primo > equals < secondo"
add alias < "primo > più < secondo" > to < "primo > plus < secondo"
add alias < "minuendo > meno < sottraendo" > to < "minuendo > minus < sottraendo"
add alias < "primo > per < secondo" > to < "primo > times < secondo"
add alias < "dividendo > diviso < divisore" > to < "dividendo > over < divisore"
add alias < "base > alla < esponente" > to < "base > to the < esponente"
add alias < "primo > è maggiore di < secondo" > to < "primo > is greater than < secondo"
add alias < "primo > è minore di < secondo" > to < "primo > is less than < secondo"
add alias < "primo > e < secondo" > to < "primo > and < secondo"
add alias < "primo > o < secondo" > to < "primo > or < secondo"
add alias < "non < condizione" > to < "not < condizione"

add alias < "lista con ..." > to < "list with ..."
add alias < "lunghezza di < lista" > to < "length of < lista"
add alias < "elemento < indice > di < lista" > to < "item < indice > of < lista"
add alias < "imposta elemento < indice > di < lista > a < valore" > to < "set item < indice > of < lista > to < valore"
add alias < "aggiungi < elemento > a < lista" > to < "append < elemento > to < lista"

add name < "Vero" > to < "True"
add name < "Falso" > to < "False"
add name < "Vuoto" > to < "Empty"
add name < "Risposta" > to < "Answer"
add name < "Lista Vuota" > to < "Empty List"

learn < "utils"

add alias < "valore > è < tipo" > to < "valore > is < tipo"
add alias < "primo > è diverso da < secondo" > to < "primo > doesn't equal < secondo"
add alias < "incrementa < variabile > di < tot" > to < "increment < variabile > by < tot"
add alias < "incrementa < variabile" > to < "increment < variabile"
add alias < "ripeti da < inizio > a < fine > su < contatore >< codice" > to < "repeat from < inizio > to < fine > on < contatore >< codice"
add alias < "ripeti < n > volte su < contatore >< codice" > to < "repeat < n > times on < contatore >< codice"
add alias < "ripeti < n > volte < codice" > to < "repeat < n > times < codice"
add alias < "ripeti per ogni < elemento > in < lista >< codice" > to < "repeat for each < elemento > in < lista >< codice"
add alias < "somma di < lista" > to < "sum of < lista"
add alias < "radice quadrata di < valore" > to < "square root of < valore"
add alias < "radice cubica di < valore" > to < "cube root of < valore"